import { createMazeLayout } from './maze';
import type { GameState, Vec2 } from './types';
export declare function toCell(x: number, y: number): Vec2;
export declare function distance(a: Vec2, b: Vec2): number;
export declare function rockAtCell(state: GameState, x: number, y: number): boolean;
export declare function gemAtCell(state: GameState, q: number, r: number): boolean;
export declare function rawGemAtCell(state: GameState, q: number, r: number): boolean;
export declare function mazeLayoutFromState(state: GameState): ReturnType<typeof createMazeLayout>;
export declare function rebuildPathNav(state: GameState): void;
export declare function canPlaceRockAt(state: GameState, x: number, y: number): boolean;
export declare function canPlaceRawGemAt(state: GameState, x: number, y: number): boolean;
export declare function canPlaceHoldGemAt(state: GameState, x: number, y: number): boolean;
export declare function canPlaceGemAt(state: GameState, x: number, y: number): boolean;
export declare function rockPathLengthDelta(state: GameState, x: number, y: number): number | null;
export declare function previewRockPath(state: GameState, x: number, y: number): number | null;
