import { getArea } from './content';
import { getGemCombatStats } from './gems';
import type { DamageType, EnemyState, GameState, GemFamilyId, GemLevel, GemState, ProjectileState, TierId, WaveSegment } from './types';
export declare function applySlowDebuff(enemy: EnemyState, level: GemLevel, factor: number, until: number): void;
export declare function effectiveSlowFactor(enemy: EnemyState, now: number): number;
export declare function applyArmorDebuff(enemy: EnemyState, level: GemLevel, reduction: number, until?: number): void;
export declare function effectiveArmorReduction(enemy: EnemyState, now?: number): number;
export declare function syncDebuffScalars(enemy: EnemyState, now: number): void;
export declare const MAX_DT = 0.05;
export declare const PROJECTILE_HIT_DISTANCE = 0.12;
export declare function spawnEnemies(state: GameState, dt: number): void;
export declare function advanceSegment(state: GameState, segments: WaveSegment[]): void;
export declare function spawnEnemy(state: GameState, enemyId: string, tier: ReturnType<typeof getArea>['tiers'][TierId]): void;
export declare function tickEnemies(state: GameState, dt: number): void;
export declare function stepFlyingEnemy(enemy: EnemyState, nav: GameState['pathNav'], dt: number): 'moving' | 'leaked';
export declare function tickGems(state: GameState, dt: number): void;
export declare function tickProjectiles(state: GameState, dt: number): void;
export declare function tickCombatStep(state: GameState, dt: number): void;
export declare function clearInactive(state: GameState): void;
export declare function hitWithProjectile(state: GameState, projectile: ProjectileState, target: EnemyState): void;
export declare function handleEnemyDeath(state: GameState, enemy: EnemyState): void;
export declare function spawnSplitEnemy(state: GameState, enemyId: string, x: number, y: number, checkpointIndex: number): void;
export declare function applyDamage(state: GameState, enemy: EnemyState, amount: number, gem: GemState | null, options: {
    shieldPierce?: number;
    bypassShield?: boolean;
    damageType?: DamageType;
}): number;
export declare function makeProjectile(state: GameState, gem: GemState, stats: ReturnType<typeof getGemCombatStats>, target: EnemyState): ProjectileState;
export declare function findGemTarget(state: GameState, gem: GemState, range: number): EnemyState | undefined;
export declare function gemCanTargetAir(family: GemFamilyId): boolean;
export declare function completeWaveOrAttempt(state: GameState): void;
