import type { GameState, GemFamilyId, GemLevel, TargetingMode, UiFeedback } from './types';
export declare function finishRocks(state: GameState): void;
export declare function placeRawGem(state: GameState, x: number, y: number): UiFeedback;
export declare function commitRawGem(state: GameState, rawGemId: number): void;
export declare function commitRawRecipe(state: GameState, recipeId: string): void;
export declare function claimOffer(state: GameState, index: number): UiFeedback;
export declare function rerollOffers(state: GameState): void;
export declare function upgradeRock(state: GameState, x: number, y: number): void;
export declare function startWave(state: GameState): void;
export declare function placeGem(state: GameState, x: number, y: number): void;
export declare function placeRock(state: GameState, x: number, y: number): UiFeedback;
export declare function sellRock(state: GameState, x: number, y: number): UiFeedback;
export declare function sellGem(state: GameState, gemId: number): void;
export declare function mergeGems(state: GameState, targetGemId: number): void;
export declare function undoMerge(state: GameState): void;
export declare function pickUpGem(state: GameState, gemId: number): void;
export declare function swapGemWithHold(state: GameState, gemId: number): void;
export declare function selectHoldGem(state: GameState): void;
export declare function placeHoldGem(state: GameState, x: number, y: number): void;
export declare function clearHold(state: GameState): void;
export declare function cycleGemTargeting(state: GameState, gemId: number): void;
export declare function setGemTargeting(state: GameState, gemId: number, mode: TargetingMode): void;
export declare function rerollQuestAction(state: GameState, questId: string): void;
export declare function addInventoryGem(state: GameState, family: GemFamilyId, level: GemLevel): void;
