import type { EnemyDefinition } from '../types';

export const enemyDefinitions: Record<string, EnemyDefinition> = {
  scout: {
    id: 'scout',
    name: 'Void Scout',
    hp: 48,
    speed: 1.75,
    rewardGold: 4,
    color: '#77e7ff',
  },
  trooper: {
    id: 'trooper',
    name: 'Astral Trooper',
    hp: 72,
    speed: 1.38,
    rewardGold: 5,
    color: '#e4e9ff',
  },
  runner: {
    id: 'runner',
    name: 'Comet Runner',
    hp: 42,
    speed: 2.35,
    rewardGold: 5,
    color: '#5eead4',
    flying: true,
  },
  bulwark: {
    id: 'bulwark',
    name: 'Shield Bulwark',
    hp: 95,
    speed: 1.05,
    rewardGold: 7,
    shield: 48,
    color: '#bd9cff',
  },
  striker: {
    id: 'striker',
    name: 'Comet Striker',
    hp: 118,
    speed: 1.58,
    rewardGold: 8,
    color: '#ffb86b',
  },
  brute: {
    id: 'brute',
    name: 'Iron Brute',
    hp: 210,
    speed: 0.88,
    rewardGold: 10,
    color: '#a78bfa',
    physicalImmune: true,
  },
  shifter: {
    id: 'shifter',
    name: 'Phase Shifter',
    hp: 88,
    speed: 1.42,
    rewardGold: 9,
    color: '#f0abfc',
    splitInto: 'scout',
    splitCount: 2,
    invisible: true,
  },
  mystic: {
    id: 'mystic',
    name: 'Void Mystic',
    hp: 135,
    speed: 1.12,
    rewardGold: 11,
    shield: 72,
    color: '#c4b5fd',
    magicImmune: true,
  },
  warden: {
    id: 'warden',
    name: 'Nebula Warden',
    hp: 175,
    speed: 1.02,
    rewardGold: 12,
    shield: 78,
    color: '#a48cff',
    flying: true,
    invisible: true,
  },
  vanguard: {
    id: 'vanguard',
    name: 'Crown Vanguard',
    hp: 240,
    speed: 0.95,
    rewardGold: 15,
    shield: 105,
    color: '#ffd166',
  },
  colossus: {
    id: 'colossus',
    name: 'Titan Colossus',
    hp: 1800,
    speed: 0.72,
    rewardGold: 80,
    shield: 320,
    color: '#f87171',
    isBoss: true,
    leakDamage: 2,
  },
  dreadnought: {
    id: 'dreadnought',
    name: 'Abyss Dreadnought',
    hp: 3200,
    speed: 0.65,
    rewardGold: 120,
    shield: 480,
    color: '#ef4444',
    isBoss: true,
    leakDamage: 3,
  },
};

export function getEnemy(enemyId: string): EnemyDefinition {
  const enemy = enemyDefinitions[enemyId];
  if (!enemy) throw new Error(`Missing enemy: ${enemyId}`);
  return enemy;
}
