import type {
  BaseGemFamilyId,
  GemDefinition,
  GemFamilyId,
  HybridGemFamilyId,
} from '../types';

export const gemDefinitions: Record<GemFamilyId, GemDefinition> = {
  kinetic: {
    id: 'kinetic',
    name: 'Kinetic Crystal',
    role: 'Rapid fire with crit bursts.',
    branch: 'kinetic',
    damageType: 'physical',
    baseDamage: 18,
    baseRange: 3.0,
    baseCooldown: 0.85,
    projectileSpeed: 9,
    color: '#7dd3fc',
    shopCost: 16,
    critChance: 0.12,
  },
  verdant: {
    id: 'verdant',
    name: 'Verdant Spore',
    role: 'Stacking poison damage over time.',
    branch: 'verdant',
    damageType: 'magic',
    baseDamage: 10,
    baseRange: 2.75,
    baseCooldown: 1.0,
    projectileSpeed: 7.5,
    color: '#66f2a4',
    shopCost: 18,
    poisonDps: 7,
    poisonDuration: 3.5,
  },
  arcane: {
    id: 'arcane',
    name: 'Arcane Lens',
    role: 'Shield-breaking precision beams.',
    branch: 'arcane',
    damageType: 'magic',
    baseDamage: 17,
    baseRange: 3.35,
    baseCooldown: 1.05,
    projectileSpeed: 10.5,
    color: '#c084fc',
    shopCost: 20,
    shieldPierce: 2.4,
  },
  nova: {
    id: 'nova',
    name: 'Nova Mortar',
    role: 'Slowing splash artillery.',
    branch: 'nova',
    damageType: 'pure',
    baseDamage: 28,
    baseRange: 2.65,
    baseCooldown: 1.75,
    projectileSpeed: 6.5,
    color: '#fb7185',
    shopCost: 22,
    splashRadius: 0.75,
    slowFactor: 0.35,
    slowDuration: 1.8,
  },
  prism: {
    id: 'prism',
    name: 'Prism Shard',
    role: 'Armor shred and bonus vs tanks.',
    branch: 'prism',
    damageType: 'physical',
    baseDamage: 15,
    baseRange: 3.1,
    baseCooldown: 0.95,
    projectileSpeed: 8.8,
    color: '#fde68a',
    shopCost: 24,
    armorReduction: 0.08,
    bonusVsHighHp: 0.25,
  },
  ember: {
    id: 'ember',
    name: 'Ember Core',
    role: 'Burn damage that stacks on repeated hits.',
    branch: 'ember',
    damageType: 'magic',
    baseDamage: 16,
    baseRange: 2.85,
    baseCooldown: 0.92,
    projectileSpeed: 8.2,
    color: '#fb923c',
    shopCost: 21,
    poisonDps: 5,
    poisonDuration: 2.5,
  },
  toxic_shot: {
    id: 'toxic_shot',
    name: 'Toxic Shot',
    role: 'Hybrid: kinetic + verdant. Crit poison darts.',
    hybrid: true,
    damageType: 'magic',
    baseDamage: 14,
    baseRange: 2.9,
    baseCooldown: 0.9,
    projectileSpeed: 8.5,
    color: '#5ee4a8',
    shopCost: 0,
    poisonDps: 9,
    poisonDuration: 2.8,
    critChance: 0.1,
  },
  plasma_mortar: {
    id: 'plasma_mortar',
    name: 'Plasma Mortar',
    role: 'Hybrid: arcane + nova. Shield-piercing splash.',
    hybrid: true,
    damageType: 'pure',
    baseDamage: 24,
    baseRange: 2.8,
    baseCooldown: 1.55,
    projectileSpeed: 6.8,
    color: '#e879f9',
    shopCost: 0,
    shieldPierce: 1.8,
    splashRadius: 0.65,
    slowFactor: 0.25,
    slowDuration: 1.4,
  },
  pierce_crystal: {
    id: 'pierce_crystal',
    name: 'Pierce Crystal',
    role: 'Hybrid: kinetic + arcane. Heavy shield break.',
    hybrid: true,
    damageType: 'physical',
    baseDamage: 22,
    baseRange: 3.2,
    baseCooldown: 1.0,
    projectileSpeed: 10,
    color: '#a5b4fc',
    shopCost: 0,
    shieldPierce: 3.2,
    critChance: 0.08,
  },
  spore_bomb: {
    id: 'spore_bomb',
    name: 'Spore Bomb',
    role: 'Hybrid: verdant + nova. AoE toxin clouds.',
    hybrid: true,
    damageType: 'magic',
    baseDamage: 18,
    baseRange: 2.7,
    baseCooldown: 1.35,
    projectileSpeed: 7,
    color: '#4ade80',
    shopCost: 0,
    poisonDps: 11,
    poisonDuration: 3.2,
    splashRadius: 0.7,
  },
  slayer_shard: {
    id: 'slayer_shard',
    name: 'Slayer Shard',
    role: 'Hybrid: prism + kinetic. Tank hunter.',
    hybrid: true,
    damageType: 'physical',
    baseDamage: 20,
    baseRange: 3.05,
    baseCooldown: 0.92,
    projectileSpeed: 9,
    color: '#fcd34d',
    shopCost: 0,
    armorReduction: 0.1,
    bonusVsHighHp: 0.35,
    critChance: 0.1,
  },
  venom_lens: {
    id: 'venom_lens',
    name: 'Venom Lens',
    role: 'Hybrid: arcane + verdant. Magic poison beam.',
    hybrid: true,
    damageType: 'magic',
    baseDamage: 16,
    baseRange: 3.25,
    baseCooldown: 1.05,
    projectileSpeed: 10.2,
    color: '#86efac',
    shopCost: 0,
    poisonDps: 12,
    poisonDuration: 3.8,
    shieldPierce: 2.0,
  },
  shatter_star: {
    id: 'shatter_star',
    name: 'Shatter Star',
    role: 'Hybrid: nova + prism. Splash armor shred.',
    hybrid: true,
    damageType: 'pure',
    baseDamage: 26,
    baseRange: 2.85,
    baseCooldown: 1.45,
    projectileSpeed: 7.2,
    color: '#fde047',
    shopCost: 0,
    splashRadius: 0.8,
    armorReduction: 0.12,
    slowFactor: 0.2,
    slowDuration: 1.2,
  },
  executioner: {
    id: 'executioner',
    name: 'Executioner',
    role: 'Hybrid: kinetic + prism. Elite finisher.',
    hybrid: true,
    damageType: 'physical',
    baseDamage: 28,
    baseRange: 3.15,
    baseCooldown: 1.1,
    projectileSpeed: 9.5,
    color: '#fbbf24',
    shopCost: 0,
    critChance: 0.18,
    bonusVsHighHp: 0.45,
    armorReduction: 0.14,
  },
  ember_lance: {
    id: 'ember_lance',
    name: 'Ember Lance',
    role: 'Hybrid: ember + kinetic. Rapid burning crits.',
    hybrid: true,
    damageType: 'magic',
    baseDamage: 20,
    baseRange: 3.0,
    baseCooldown: 0.82,
    projectileSpeed: 9.2,
    color: '#fdba74',
    shopCost: 0,
    poisonDps: 8,
    poisonDuration: 2.2,
    critChance: 0.14,
  },
  solar_flare: {
    id: 'solar_flare',
    name: 'Solar Flare',
    role: 'Hybrid: ember + nova. Burning splash artillery.',
    hybrid: true,
    damageType: 'pure',
    baseDamage: 26,
    baseRange: 2.75,
    baseCooldown: 1.5,
    projectileSpeed: 6.6,
    color: '#f97316',
    shopCost: 0,
    poisonDps: 10,
    poisonDuration: 2.8,
    splashRadius: 0.72,
    slowFactor: 0.22,
    slowDuration: 1.3,
  },
};

export const BASE_GEM_FAMILIES: BaseGemFamilyId[] = [
  'kinetic',
  'verdant',
  'arcane',
  'nova',
  'prism',
  'ember',
];

export const HYBRID_GEM_FAMILIES: HybridGemFamilyId[] = [
  'toxic_shot',
  'plasma_mortar',
  'pierce_crystal',
  'spore_bomb',
  'slayer_shard',
  'venom_lens',
  'shatter_star',
  'executioner',
  'ember_lance',
  'solar_flare',
];
